### ISSUE TITLE
method_save?

### ISSUE THREAD

**Issue by BufuWinner** [An0nimia/deezloader#1]
Hi An0nimia, I'm happy the project came back since I used it in one of mine too  :)
I've seen in the new version that there's this new param called "method_save", the question is how to use this option when downloading songs?
I've tried myself to search through the code but got nothing useful.  

So far the differences I've seen are:
method_save=0
-> Throws error: ```KeyError: 'discnumber'```  

method_save=1
-> Works fine

method_save=2
-> It's somehow slower and not always works when trying to move the file

Could you please explain what they each do?
Thanks in advance!

**Comment by Samfun75** [comment]
if method_save == 0:
			zip_name = f"{album}"

		elif method_save == 1:
			artist = __var_excape(song_metadata['ar_album'])
			zip_name = f"{album} - {artist}"

		elif method_save == 2:
			artist = __var_excape(song_metadata['ar_album'])
			upc = song_metadata['upc']
			zip_name = f"{album} - {artist} {upc}"

That option is used to name the zip file.

**Comment by An0nimia** [comment]
Ups I didn't see this, yes that is right the method save is the preferable format how to save the tracks, you can try all 3 and see the difference between them.

P.S. that keyerror should be solved and sorry again for my late reply :)
