### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by cyberboysumanjay** [An0nimia/deezloader#13]
I tried to run the script and it gave me this error each time
> deezloader.BadCredentials: Wrong token :(

I have tried with 3 different account and got arl from Chrome Cookies which is valid and is of 192 chars.
Here is my script which I ran after installing Deezloader from pip3
https://del.dog/ejohopiqoh.php

Can you please throw some light on it?

**Comment by An0nimia** [comment]
@cyberboysumanjay Why have you put token"? delete that "

**Comment by cyberboysumanjay** [comment]
Yeah, my bad I just edited it for posting here. I tried the right way too but it there the same error.

**Comment by An0nimia** [comment]
@cyberboysumanjay Are you sure that the arl token is right?

**Comment by cyberboysumanjay** [comment]
Yes, I extracted it from cookies just before running script!

**Comment by cyberboysumanjay** [comment]
Is there anything like IP Limitations too? Like I can't login if Deezer isn't available in my country and  I've to process the request via proxy?

**Comment by An0nimia** [comment]
@cyberboysumanjay Most probably yes try with proxychains

**Comment by cyberboysumanjay** [comment]
Tried with a US Server and it worked fine for me. 
Thanks alot.
One more quick question. Do arl token expires after a certain time?

**Comment by An0nimia** [comment]
@cyberboysumanjay Ya
