### ISSUE TITLE
2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by 9Mad-Max5** [An0nimia/deezloader#18]
Issue while calling deezloader

`Traceback (most recent call last):
  File "Deezloadebot/dwsongs-normal.py", line 54, in <module>
    downloa = deezloader.Login(mail, password, deezer_token)
TypeError: __init__() takes 2 positional arguments but 4 were given
`

**Comment by An0nimia** [comment]
@9Mad-Max5 I have to update the README.md, but hey let try to solve it by yourself, if you know a bit of python it shouldn't be hard ;)

**Comment by 9Mad-Max5** [comment]
I just give the class Login 3 Arguments.
But if i get it right it just needs 2.
(self, token):
But I#m not sure what is ment with the variable self.

Maybe I have a closer look this evening.

**Comment by An0nimia** [comment]
@9Mad-Max5 See you resolved by yourself

**Comment by aryanvikash** [comment]
> I just give the class Login 3 Arguments.
> But if i get it right it just needs 2.
> (self, token):
> But I#m not sure what is ment with the variable self.
> 
> Maybe I have a closer look this evening.

_Yeah It Only Needs a Token Variable_

**Comment by 9Mad-Max5** [comment]
yup just the tokens work thanks
