### ISSUE TITLE
Unicode chars

### ISSUE THREAD

**Issue by kilkujadek** [An0nimia/deezloader#22]
It is not possible to save songs with (some?) unicode chars, no matter it is an album or playlist

```
File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
UnicodeEncodeError: 'ascii' codec can't encode character '\u015b' in position 21: ordinal not in range(128)
```

**Comment by An0nimia** [comment]
@kilkujadek Use python 3

**Comment by kilkujadek** [comment]
It is Python 3.7.4

**Comment by An0nimia** [comment]
@kilkujadek What are the characters?

**Comment by kilkujadek** [comment]
@An0nimia Sorry, I've mix up machines - where this error was thrown it was Python 3.5

It is working fine on 3.7.4
