### ISSUE TITLE
Specify license 

### ISSUE THREAD

**Issue by Newbytee** [An0nimia/deezloader#24]
Hi. It would be nice if you could give the project a license, assuming it isn't intentionally unlicensed.

**Comment by An0nimia** [comment]
@Newbytee https://github.com/An0nimia/deezloader/blob/master/README.md am I joke for you?

**Comment by Newbytee** [comment]
> @Newbytee https://github.com/An0nimia/deezloader/blob/master/README.md am I joke for you?

I am blind.

**Comment by An0nimia** [comment]
@Newbytee It is fine :)
