### ISSUE TITLE
Documentation in README is out of date

### ISSUE THREAD

**Issue by Newbytee** [An0nimia/deezloader#25]
In README.md, the code sample for initialising the library tells you to pass a username, password, and token to the constructor of Login, however in the current state of the code this is not the case as it only asks for a token. See here: 
![image](https://user-images.githubusercontent.com/4428753/70348497-14527a80-1863-11ea-9e25-19f33c7cbfb3.png)

**Comment by An0nimia** [comment]
@Newbytee You are right I will modify the readme
