### ISSUE TITLE
deezloader.Login() requires Deezer token despite that the resulting object can be used without it

### ISSUE THREAD

**Issue by Newbytee** [An0nimia/deezloader#26]
`deezloader.Login()` should not require the token parameter as the resulting object can be used to download tracks from Spotify without it. Making this parameter optional or separating it into one instantiator for Spotify and one for Deezer would both be sensible solutions in my view (though, the latter might be less desirable as it could be API-breaking).

**Comment by An0nimia** [comment]
@Newbytee Is this an issue? 
Fork the repo and do it by yourself.
