### ISSUE TITLE
Problem with config file

### ISSUE THREAD

**Issue by sm01man** [An0nimia/deezloader#27]
I'm running Arch Linux, when I try to run the script I get this issue:

`┌─[sm0lman@sm0lman-ARCH] - [~] - [Wed Dec 18, 09:46]
└─[$] <> deez-dw

usage: deez-dw [-h] [-l LINK] [-s SONG] [-a ARTIST] [-o OUTPUT] [-q QUALITY] [-rq RECURSIVE_QUALITY] [-rd RECURSIVE_DOWNLOAD] 
deez-dw: error: the following arguments are required: setting
`

**Comment by Mushebeq** [comment]
Did you read the readme file?

**Comment by An0nimia** [comment]
@Mushebeq Thanks :)

**Comment by sm01man** [comment]
Ok, I guess I meant where is the setting.ini file? When I run 'deez-dw setting' it says 'something went wrong with the configuration file.' I installed via the AUR but I would be happy to install manually.

**Comment by sm01man** [comment]
Ok, I figured out that the settings.ini file has to be in the working directory, sorry it was just a bit odd as usually config files would be located elsewhere.
