### ISSUE TITLE
Own name of file outputs

### ISSUE THREAD

**Issue by Encryptize** [An0nimia/deezloader#28]
Add a option for make own creating name of downloaded files. I want to get output like this: "(Artist) - (Title of song)" or "(Artist) - (Album name)".

**Comment by An0nimia** [comment]
@Encryptize If there is something which I won't do, this is on of them :)

**Comment by Encryptize** [comment]
> @Encryptize If there is something which I won't do, this is on of them :)

But actually way to name file is very bad. _(Album name) CD 1 TRACK 1 **(FLAC)**_ isn't readable in folder without opening file for get info, what is name of track. If you want output like this, make a option for create own name for files output.

**Comment by An0nimia** [comment]
@Encryptize Song Tags metadata: am I a joke for you?

The code is open source if you don't like modify it by your own

**Comment by divadsn** [comment]
![Screenshot_20200317_151723](https://user-images.githubusercontent.com/28547847/76865065-6b082100-6862-11ea-9bf0-4b464d9a7544.png)

Subfolders: Am I a joke to you?
