### ISSUE TITLE
Name of Downloaded File

### ISSUE THREAD

**Issue by SPITereum** [An0nimia/deezloader#29]
Hi, thank you for this code. I love this program. So...
Why file name downloaded doesn't have the properly name of song?
While file are downloading, and progress command line bar is showed up, i can see the right name. There is a method to get that name? Or a thing to do to have the right name in file downloaded?
Excuse me for my bad english, i have tried to explain it at best i can.
Thank you.

**Comment by An0nimia** [comment]
@SPITereum nope

**Comment by SPITereum** [comment]
Ok, thank you for reply
