### ISSUE TITLE
__init__.py empty

### ISSUE THREAD

**Issue by IvoryJam** [An0nimia/deezloader#3]
\_\_init\_\_.py is empty in the main folder so can't use the library `from deezloader import Login` removed all my packages and did a pip install and it's still blank
![image](https://user-images.githubusercontent.com/35709713/141234053-269fa6ed-e06b-41dc-abe8-881ea8c66a15.png)

**Comment by IvoryJam** [comment]
Looks like the most recent one that works was the 9.22 update, not sure what happened but that's the one that works for me

**Comment by An0nimia** [comment]
I updated it, I didn't write a documentation, anyway you should understand how the library works, see my https://github.com/An0nimia/DeezSpot_bot.
