### ISSUE TITLE
Deezer API patch

### ISSUE THREAD

**Issue by ItzLuk3** [An0nimia/deezloader#32]
Deezer changed the API so every filesize other than 128 returns 0 on free accounts
they still serve the files tho, so it should be fixable

Read more here: https://www.reddit.com/r/DeezloadersIsBack/comments/gdc0rm/deezer_patched_the_api_again/

**Comment by An0nimia** [comment]
Solved. Close if you agree. Thanks =)

**Comment by ItzLuk3** [comment]
GG Ez
