### ISSUE TITLE
Update code

### ISSUE THREAD

**Issue by Chostakovitch** [An0nimia/deezloader#33]
Hello @An0nimia,

Yesterday, when trying to download a playlist, I noticed that some songs won't work (no data).
Trying `deemix` I managed to get it work.

But I prefer using this version of `deezloader`, so I checked to code to understand. 

For whatever reason and AFAIU the `playlist.getSongs` method is now used rather than the `api.deezer.com/playlist` endpoint. The former returns a `FALLABACK` object with an alternative song id. If the main ID gets a no data we can use the fallback ID.

Anyway, I tried a quick fix directly in the Python package files, and it works. 

I wanted to submit a pull request, but I then noticed that the code of this repository is older than the code downloaded with the Python package.

I am committed to work on a proper fix, including for songs alone, even if I'm not really a developer.

Could you please update the repository code ?

**Comment by An0nimia** [comment]
Too late =), thanks for gave me this input =)
