### ISSUE TITLE
does method for (Q1) album_art as .jpeg method exist? (Q2)  song_lyric file as .lrc exist? IF NOT any suggestion to add it.   

### ISSUE THREAD

**Issue by delta-ij** [An0nimia/deezloader#35]

**Comment by delta-ij** [comment]
i think there is option, but there is no mention in readme :( 
like when calling this method, we have control over selecting album-art & .lrc file or not :
`downloa.download_trackdee(
	"Insert the Spotify link of the track to download",
	output = "SELECT THE PATH WHERE SAVE YOUR SONGS",
	quality = "MP3_320",
	recursive_quality = False,
	recursive_download = False
	not_interface = False
)`

**Comment by An0nimia** [comment]
Absolutely no. The pics are all downloaded 1200x1200 quality.
