### ISSUE TITLE
deez-dw: command not found

### ISSUE THREAD

**Issue by MohammadGIV** [An0nimia/deezloader#36]
Hi
I Installed Deezloader using the given command in the main page but when I run deez-dw command I get this error:
deez-dw: command not found
python3 and pip3 are installed correctly.

**Comment by An0nimia** [comment]
@MohammadGIV deez-dw.py

**Comment by MohammadGIV** [comment]
Thanks
and now I get this error with every command and argument: 



usage: deez-dw.py [-h] [-l LINK] [-s SONG] [-a ARTIST] [-o OUTPUT]
                  [-q QUALITY] [-rq RECURSIVE_QUALITY]
                  [-rd RECURSIVE_DOWNLOAD] [-g NOT_GUI] [-z ZIP]
                  setting
deez-dw.py: error: the following arguments are required: setting

**Comment by Mushebeq** [comment]
@MohammadGIV 
![image](https://user-images.githubusercontent.com/37749104/93723713-a2f17780-fba9-11ea-83bf-0e6165209f92.png)

**Comment by An0nimia** [comment]
@MohammadGIV Read the Readme
