### ISSUE TITLE
Random numbers in album title

### ISSUE THREAD

**Issue by IvoryJam** [An0nimia/deezloader#39]
Getting random numbers in title when using a link to Spotify
The album folder is like "Album 075679960665"

```import deezloader
d = deezloader.Login('token_here')
d.download_trackspo(
    URL = 'link_to_spotify_song',
    output = 'output_folder',
    quality = "FLAC",
    recursive_quality = True,
    recursive_download = True,
    not_interface = False,
)

**Comment by An0nimia** [comment]
@IvoryJam That is the upc of the album unique for every album which exists in this world. IT IS NOT A BUG.

**Comment by IvoryJam** [comment]
I see, what about the song titles? Because those are the album title, CD 1 TRACK 1 (FLAC).flac

I went through the code and didn't see a way to pull the album title and song title.

**Comment by IvoryJam** [comment]
Either way, it's great work! Worst case is I can read the metadata and update the track's filenames

**Comment by An0nimia** [comment]
@IvoryJam It was the only way to avoid tracks with the same title or tracks with strange ascii char and bigger than 255 etc

**Comment by IvoryJam** [comment]
@An0nimia Oh, I see! Well thank you! I'll close the issue!
