### ISSUE TITLE
Help, please.

### ISSUE THREAD

**Issue by thonsouza** [An0nimia/deezloader#7]
Hello, congratulations to the time you spent on this work. I am a layman, I can not use to do the installation of pip3 and I executed the command pip3 install deezloader, until then everything ok.

I'm running the commands like this:

```
$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deezloader
>>> downloa = deezloader.Login (thon@gmail.com, hsaiuwwas)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'thon' is not defined
```

Some help, please. A brief execution tutorial would help. Sorry, but I do not know what to do.

**Comment by An0nimia** [comment]
@thonsouza are you new with coding?

**Comment by thonsouza** [comment]
Yes friend. I'm just curious, but I could not understand. I am a linux user, but I do not understand anything about python. Sorry to bother you, I did a little research, but I still got the way to the execution.

**Comment by thonsouza** [comment]
@An0nimia It would not be for me, would it?

**Comment by An0nimia** [comment]
@thonsouza import deezloader
downloa = deezloader.Login("thg1@outlook.com", "hsaiuwwas") 
Variables are not defined

**Comment by thonsouza** [comment]
@An0nimia  Where do I define these variables?

**Comment by An0nimia** [comment]
@thonsouza You have to know the basic coding rules
