### ISSUE TITLE
Customize songs' filename

### ISSUE THREAD

**Issue by edoaxyz** [An0nimia/deezloader#9]
Hi, is it possible to customize the filename of the songs? I'm asking this because I'm trying to save those files in a FAT-32 usb and it doesn't support special characters like `:` or `(`, while the song are named with those characters. Maybe you can add an optional argument for specifying the filename using strings with [named placeholders](https://pyformat.info/#named_placeholders).

**Comment by An0nimia** [comment]
Yes it is possible, you can clone my repository and improve yourself and do what you prefer :)
